---
# tasks file for heartbeat

- name: Install heartbeat packages
  apt:
    name: 'heartbeat'
    state: 'present'
    update_cache: 'yes'
  tags: [heartbeat,packages]

- name: Install custom resources
  template:
    src: 'resources/{{ item }}.j2'
    dest: '/etc/ha.d/resource.d/{{ item }}'
    owner: 'root'
    group: 'root'
    mode: '0755'
  with_items: heartbeat_custom_resources
  tags: [heartbeat]

- name: Configure heartbeat
  template:
    src: 'ha.cf.j2'
    dest: '/etc/ha.d/ha.cf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: Restart heartbeat
  tags: [heartbeat,configuration]

- name: Define authkeys
  template:
    src: 'authkeys.j2'
    dest: '/etc/ha.d/authkeys'
    owner: 'root'
    group: 'root'
    mode: '0600'
  notify: Restart heartbeat
  tags: [heartbeat,configuration]

- name: Define resources
  template:
    src: 'haresources.j2'
    dest: '/etc/ha.d/haresources'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: Restart heartbeat
  tags: [heartbeat,configuration]

- name: Ensure heartbeat is started and enabled at boot
  service:
    name: 'heartbeat'
    state: 'started'
    enabled: 'yes'
  tags: [heartbeat,services]