---
# tasks file for initial-setup

- name: Set hostname
  shell: hostnamectl set-hostname '{{ inventory_hostname }}'
  when: ansible_hostname != inventory_hostname
  register: set_hostname
  tags: [initial-setup,hostname]

- name: Reload facts
  setup:
  when: set_hostname.changed
  tags: [initial-setup,hostname]

- name: Update /etc/hosts
  lineinfile:
    dest: '/etc/hosts'
    regexp: '^127\.0\.0\.1'
    line: '127.0.0.1 localhost {{ inventory_hostname }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  tags: [initial-setup,hostname]

- name: Update apt packages
  apt:
    update_cache: 'yes'
    cache_valid_time: '86400'
  tags: [initial-setup,apt]

- name: Upgrade server
  apt: 
    upgrade: 'full'
  when: initial_setup_full_upgrade
  tags: [initial-setup,apt]

- name: Install ntp server
  apt:
    name: 'ntp'
    state: 'present'
  tags: [initial-setup,ntp]

- name: Start the ntp service
  service:
    name: 'ntp'
    state: 'started'
    enabled: 'yes'
  tags: [initial-setup,ntp]
