---
# tasks file for fcgiwrap

- name: Install fcgiwrap package
  apt:
    name: 'fcgiwrap'
    state: 'latest'
  tags: [fcgiwrap,packages]

- name: Enable fcgiwrap service
  service:
    name: 'fcgiwrap'
    enabled: 'yes'
  tags: [fcgiwrap,services]