---
# tasks file for rabbitmq

- name: Add rabbitmq apt key
  apt_key:
    url: '{{ rabbitmq_url_key }}'
    state: present
  tags: [rabbitmq,packages]

- name: Add rabbitmq repo
  apt_repository:
    repo: '{{ rabbitmq_apt_repo }}'
    state: 'present'
    update_cache: 'yes'
  tags: [rabbitmq,packages]

- name: Install rabbitmq package
  apt:
    name: 'rabbitmq-server'
    state: 'present'
  tags: [rabbitmq,packages]

- name: Configure rabbitmq
  template:
    src: 'rabbitmq.config.j2'
    dest: '/etc/rabbitmq/rabbitmq.config'
    owner: 'rabbitmq'
    group: 'rabbitmq'
    mode: '0644'
  notify: Restart rabbitmq
  tags: [rabbitmq]

- name: Manage users
  rabbitmq_user:
    configure_priv: '{{ item.configure_priv }}'
    force: 'yes'
    password: '{{ item.password }}'
    read_priv: '{{ item.read_priv }}'
    state: 'present'
    user: '{{ item.user }}'
    tags: '{{ item.tags }}'
    vhost: '{{ item.vhost }}'
    write_priv: '{{ item.write_priv }}'
  with_items: '{{ rabbitmq_users }}'
  tags: [rabbitmq]

- name: Enable plugins
  rabbitmq_plugin:
    names: '{{ item }}'
    state: 'enabled'
  with_items: '{{ rabbitmq_enabled_plugins }}'
  tags: [rabbitmq]

- name: Ensure rabbitmq is started and enabled on boot
  service:
    name: 'rabbitmq-server'
    state: 'started'
    enabled: 'yes'
  tags: [rabbitmq,services]