---
# tasks file for ssh-key

- name: Create .ssh directory
  file:
    dest: '~{{ ssh_key_user }}/.ssh'
    state: 'directory'
    owner: '{{ ssh_key_user }}'
    group: '{{ ssh_key_group }}'
    mode: '0700'
  tags: [ssh-key]

- name: Install key for ssh connections
  copy:
    src: '{{ ssh_key_private_key }}'
    dest: '{{ ssh_key_filename }}'
    owner: '{{ ssh_key_user }}'
    group: '{{ ssh_key_group }}'
    mode: '0600'
    force: '{{ ssh_key_force }}'
  register: ssh_key_private_key_copy
  tags: [ssh-key]

- name: Decrypt rsa key
  shell: openssl aes-256-cbc -salt -a -d -in {{ ssh_key_filename }} -out {{ ssh_key_filename }}.dec -k {{ ssh_key_password }}
  when: ssh_key_private_key_copy.changed
  tags: [ssh-key]

- name: Rename decrypted key
  shell: mv {{ ssh_key_filename }}.dec {{ ssh_key_filename }}
  when: ssh_key_private_key_copy.changed
  tags: [ssh-key]

- name: Set file permissions
  file:
    path: '{{ ssh_key_filename }}'
    owner: '{{ ssh_key_user }}'
    group: '{{ ssh_key_group }}'
    mode: '0600'
  tags: [ssh-key]
