---
# tasks file for newrelic

- name: Add newrelic apt key
  apt_key:
    url: '{{ newrelic_url_key }}'
    state: 'present'
  tags: [newrelic,packages]

- name: Add newrelic repos
  apt_repository:
    state: 'present'
    repo: '{{ newrelic_apt_repo }}'
    update_cache: 'yes'
  tags: [newrelic,packages]

- name: Install newrelic apm
  include: newrelic_apm.yml
  when: newrelic_agent_type is defined
  tags: [newrelic]

- name: Install newrelic sysmond
  include: newrelic_sysmond.yml
  when: newrelic_sysmond_install
  tags: [newrelic]
