---
# tasks file for newrelic-apm

- name: Install the newrelic packages
  apt:
    name: '{{ item }}'
    state: 'present'
  with_items: newrelic_packages
  tags: [newrelic,newrelic-apm,packages]

- name: Ensure configuration file exists (newrelic daemon needs it, even empty)
  file:
    path: '{{ newrelic_conf_file }}'
    state: 'touch'
    owner: 'root'
    group: 'root'
    mode: '0644'
  tags: [newrelic,newrelic-apm,configuration]

- name: Configure newrelic daemon
  ini_file:
    dest: '{{ newrelic_conf_file }}'
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items: newrelic_options
  notify: Restart newrelic
  tags: [newrelic,newrelic-apm,configuration]

- name: Ensure newrelic-daemon is started and enabled on boot
  service:
    name: 'newrelic-daemon'
    state: 'started'
    enabled: 'yes'
  tags: [newrelic,newrelic-apm,services]

- name: Install newrelic PHP agent
  include: newrelic_php.yml
  when: newrelic_agent_type == 'php'
  tags: [newrelic,newrelic-apm]

