---
# tasks file for deployment

- name: Configure {{ deployment_user }}
  user:
    name: '{{ deployment_user }}'
    shell: '/bin/bash'
  tags: [deployment]

- name: Ensure {{ deployment_root }} exists and belongs to {{ deployment_user }}
  file:
    dest: '{{ deployment_root }}'
    state: 'directory'
    owner: '{{ deployment_user }}'
    group: '{{ deployment_group }}'
    mode: '0775'
  when: deployment_root_type != 'nfs'
  tags: [deployment]

- name: Ensure {{ deployment_extra_dirs }} exist and belong to {{ deployment_user }}
  file:
    dest: '{{ item }}'
    state: 'directory'
    owner: '{{ deployment_user }}'
    group: '{{ deployment_group }}'
    mode: '0775'
  with_items: deployment_extra_dirs
  tags: [deployment]

- name: Install some packages
  apt:
    name: '{{ item }}'
    state: 'present'
    update_cache: 'yes'
  with_items: '{{ deployment_packages|union(deployment_extra_packages) }}'
  tags: [deployment,packages]

- name: Add authorized keys
  authorized_key:
    user: '{{ deployment_user }}'
    key: '{{ item }}'
  with_file: deployment_authorized_keys
  when: deployment_authorized_keys is defined
  tags: [deployment]

- name: Include deployment php
  include: 'php.yml'
  when: deployment_type_php
  tags: [deployment]