---
# tasks file for filesystem

- name: Ensure device is formatted
  filesystem:
    dev: '{{ item.device }}'
    fstype: '{{ item.type }}'
  with_items: filesystem_fs
  when: item.type != 'none'
  tags: [filesystem]

- name: Ensure volume is mounted
  mount:
    name: '{{ item.mountpoint }}'
    src: '{{ item.device }}'
    fstype: '{{ item.type }}'
    opts: '{{ item.opts|default("defaults,nobootwait") }}'
    state: 'mounted'
  with_items: filesystem_fs
  tags: [filesystem]
