---
# tasks file for php

- name: Install ondrej repo for latest PHP packages
  apt_repository:
    repo: '{{ php_ondrej_repo }}'
  tags: [php,packages]

- name: Install the php packages
  apt:
    name: '{{ item }}'
    state: 'present'
    update_cache: 'yes'
  with_items: php_packages
  tags: [php,packages]

- name: Install the php modules
  apt:
    name: '{{ item }}'
    state: 'present'
    update_cache: 'yes'
  with_items: php_modules
  tags: [php,packages]

- name: Configure php cli
  ini_file:
    dest: '{{ php_cli_ini_file }}'
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items: php_cli_options
  tags: [php,configuration]

- name: Include php_type tasks
  include: '{{ php_type }}.yml'
  tags: [php]