---
# tasks file for php

- name: Install ondrej repo for latest PHP packages
  apt_repository:
    repo: '{{ php_ondrej_repo }}'
  when: php_use_ondrej
  tags: [php,packages]

- name: Include cli tasks
  include: 'cli.yml'
  when: php_cli
  tags: [php,php-cli]

- name: Include fpm tasks
  include: 'fpm.yml'
  when: php_fpm
  tags: [php,php-fpm]

- name: Include mod tasks
  include: 'mod.yml'
  when: php_mod
  tags: [php,php-mod]

- name: Install the php modules
  apt:
    name: '{{ item }}'
    state: 'present'
    update_cache: 'yes'
  with_items: php_modules
  tags: [php,packages]
