---
# tasks file for php_mod

- name: Include the php_mod variables
  include_vars: "mod.yml"
  tags: [php,php-mod]

- name: Install the php_mod packages
  apt:
    name: '{{ item }}'
    state: 'present'
    update_cache: 'yes'
  with_items: php_mod_packages
  tags: [php,php-mod,packages]

- name: Configure php_mod
  ini_file:
    dest: '{{ php_mod_ini_file }}'
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items: php_mod_options
  notify: Restart apache
  tags: [php,php-mod,configuration]
