---
# tasks file for jenkins

- name: Install required packages
  apt:
    name: 'openjdk-7-jre-headless'
    state: 'installed'
  tags: [jenkins,packages]

- name: Add jenkins apt key
  apt_key:
    url: '{{ jenkins_url_key }}'
    state: 'present'
  tags: [jenkins,packages]

- name: Add jenkins repo
  apt_repository:
    state: 'present'
    repo: '{{ jenkins_apt_repo }}'
    update_cache: 'yes'
  tags: [jenkins,packages]

- name: Prevent jenkins to start on install
  copy:
    src: 'policy-rc.d'
    dest: '/usr/sbin/policy-rc.d'
    owner: 'root'
    group: 'root'
    mode: '0755'
  tags: [jenkins]

- name: Install jenkins
  apt:
    name: 'jenkins'
    state: 'present'
  tags: [jenkins,packages]

- name: Remove policy-rc.d
  file:
    name: '/usr/sbin/policy-rc.d'
    state: 'absent'
  tags: [jenkins]

- name: Ensure some dirs exist and belong to {{ jenkins_user }}
  file:
    dest: '{{ item }}'
    state: 'directory'
    owner: '{{ jenkins_user }}'
    group: '{{ jenkins_group }}'
    mode: '0775'
  with_items:
    - '{{ jenkins_log_dir }}'
    - '{{ jenkins_cache_dir }}'
  tags: [jenkins]

- name: Configure jenkins {{ jenkins_conf_file }}
  template:
    src: 'default-jenkins.j2'
    dest: '{{ jenkins_conf_file }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 
    - Restart jenkins 
  tags: [jenkins,configuration]

- name: Ensure jenkins is started and enabled at boot
  service:
    name: 'jenkins'
    state: 'started'
    enabled: 'yes'
  tags: [jenkins,services]