---
# tasks file for rsyslog

- name: Install adiscon repo for latest rsyslog package
  apt_repository:
    repo: 'ppa:adiscon/v8-stable'
  tags:
    - packages
    - rsyslog

- name: Install the rsyslog package
  apt:
    name: 'rsyslog'
    state: 'latest'
    update_cache: 'yes'
  tags:
    - packages
    - rsyslog

- name: Configure rsyslog
  template:
    src: 'rsyslog.conf.j2'
    dest: '/etc/rsyslog.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: restart rsyslog
  tags:
    - configuration
    - rsyslog

- name: Enable custom configs
  template:
    src: '{{ item.template }}'
    dest: '/etc/rsyslog.d/{{ item.order }}-{{ item.name }}.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items: '{{ rsyslog_confs }}'
  notify: restart rsyslog
  tags:
    - configuration
    - rsyslog
