---
# tasks file for sshd

- name: Setup /etc/ssh/sshd_config
  template:
    src: 'sshd_config.j2'
    dest: '/etc/ssh/sshd_config'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: sshd test and restart
  tags: [sshd]