---
# tasks file for mysql-server

- name: Install the mysql packages
  apt:
    name: '{{ item }}'
    state: 'installed'
  with_items:
    - python-selinux
    - mysql-server-{{ mysql_server_version }}
    - python-mysqldb
  tags: [mysql-server,packages]

- name: Configure mysql-server (my.cnf)
  template:
    src: 'my.cnf.j2'
    dest: '/etc/mysql/my.cnf'
  notify:
    - Restart mysql
  tags: [mysql-server,configuration]

- name: Ensure anonymous users are not in the database
  mysql_user:
    name: ''
    host: '{{ item }}'
    state: 'absent'
  with_items:
   - localhost
   - '{{ ansible_hostname }}'
  tags: [mysql-server,configuration]

- name: Remove the test database
  mysql_db:
    name: 'test'
    state: 'absent'
  tags: [mysql-server,configuration]

- name: Update mysql root password for all root accounts
  mysql_user:
    name: 'root'
    host: '{{ item }}'
    password: '{{ mysql_pass }}'
    priv: '*.*:ALL,GRANT'
  with_items:
   - '{{ ansible_hostname }}'
   - 127.0.0.1
   - ::1
   - '%'
   - localhost
  tags: [mysql-server,configuration]

- name: Copy .my.cnf file with root credentials
  template:
    src: '.my.cnf.j2'
    dest: '~/.my.cnf'
    mode: '0600'
  tags: [mysql-server,configuration]
